networks:
  proxy:
    external: true

volumes:
  app-db:

services:
  # Application Service
  app:
    container_name: citizen-security-app
    build: .
    tty: true
    depends_on:
      - db


  # Database Service
  db:
    image: mariadb
    volumes:
      - app-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: citizen-security-app
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password


  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    tty: true
    networks:
      - proxy
      - default
    volumes:
      - ./:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
    labels:
      # HTTP
      - traefik.enable=true
      - traefik.http.routers.citizen-security.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.citizen-security.entrypoints=http
      - traefik.http.routers.citizen-security.middlewares=citizen-security-https-redirect
      - traefik.http.middlewares.citizen-security-https-redirect.redirectscheme.scheme=https
      - traefik.http.services.citizen-security.loadbalancer.server.port=80
     # HTTPS
      - traefik.http.routers.citizen-security-secure.tls=true
      - traefik.http.routers.citizen-security-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.citizen-security-secure.entrypoints=https
      - traefik.http.routers.citizen-security-secure.tls.certresolver=production
