volumes:
    app-db:

services:
  # Application Service
  app:
    container_name: citizen-security-app
    build: .
    tty: true
    depends_on:
      - db


  # Database Service
  db:
    image: mariadb
    volumes:
      - app-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: citizen-security-app
      MARIADB_USER: root
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: password


  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8083:80"
    tty: true
    volumes:
      - ./:/var/www/app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db
